version: "3.9"

services:
  postgis:
    image: postgis/postgis:16-3.4
    container_name: indoor_postgis
    restart: always
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    networks:
      - indoor_net

  api:
    build: ./api
    container_name: indoor_api
    restart: always
    depends_on:
      - postgis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgis:5432/gis
      EXPORT_RESULT_DIR: /data/result
      IMPORT_BASE_PATH: /data
    ports:
      - "8001:8000"

    # The issue is that your MongoDB is running as a Replica Set.
    # When the client connects (even using the IP 10.77.159.237), the MongoDB server responds with its configuration: "I am part of a replica set, and my canonical hostname is 3dm-db4."
    # The driver then tries to verify/connect using that hostname 3dm-db4.
    # On your Windows Machine: The DNS (or hosts file) resolves 3dm-db4 correctly.
    # Inside the Container: It has no idea who 3dm-db4 is, so it fails with Name or service not known.
    # I have updated your docker-compose.dev.yml to manually "teach" the container that 3dm-db4 refers to 10.77.159.237.
    # You need to restart your containers for this to take effect:
    extra_hosts:
      - "3dm-db4:10.77.159.237"
    volumes:
      - ./data:/data
    networks:
      - indoor_net

volumes:
  postgis_data:

networks:
  indoor_net:
    driver: bridge
